Change mode selection tokens into cmdline options
This allows to use the output of "rc4csprng10" unmodified, avoiding the
need for an additional filter in the overall command pipeline.

diff --git a/sbox10 b/sbox10
--- a/sbox10
+++ b/sbox10
@@ -1,7 +1,7 @@
 #! /bin/sh
 version() {
 	cat << ===
-Version 2021.22
+Version 2021.22.1
 
 Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
 
@@ -12,74 +12,75 @@ Distribution is permitted under the terms of the GPLv3.
 
 help() {
 	cat << ===
-$APP - use an s-box to transform the input data, and modify the s-box after|
+$APP - use an s-box to transform the input data, and modify the s-box after |
 every step|
 |
 Usage: $APP [ <options> ] [ -- ] < <input_stream>|
 |
-$APP reads ASCII words (separated by whitespace, including newline sequences)|
-from standard input and interprets them according to one of the two following|
-formats:|
+$APP reads ASCII words (separated by whitespace, including newline sequences) |
+from standard input and interprets them according to one of the following |
+format:|
 |
-E <key256> <pairs>|
-|
-D <key256> <pairs>|
+<key256> <pairs>|
 |
 where|
 |
-"E", "D": these literal one-character words represent themselves.|
+<key256>: 256 decimal values in the range 0 through 255 (inclusive) which |
+determine the initial setup of the s-box. They will be used as follows: |
+Initially, the s-box (which is a array with 256 entries and its first index |
+is 0) is set to the identity permutation, i. e. contains the values 0 through |
+255. After that, all 256 values of <key256> are used to swap two s-box |
+entries: The entry with index <i> and the entry with the index equal to the |
+<i>th value of <key256>, where <i> runs from 0 through 255.|
 |
-<key256>: 256 decimal numbers in the range 0 through 255 (inclusive) which|
-determine the initial setup of the s-box. They will be used as follows:|
-Initially, the s-box (which is a array with 256 entries and its first index|
-is 0) is set to the identity permutation, i. e. contains the numbers 0|
-through 255. After that, all 256 numbers of <key256> are used to swap two|
-s-box entries: The entry with index <i> and the entry with the index equal to|
-the <i>th number of <key256>, where <i> runs from 0 through 255.|
-|
-"D" ... <pairs>: Decrypt all following input data, interpreting it as an|
-arbitrary number of pairs of decimal numbers. The first number in every pair|
-is a number to be decrypted, and the second number must have been created by|
-a cryptographic pseudo-random generator. The decryption consists of emitting|
-the current s-box value indexed by the first number. After this, the s-box|
-entry just output is swapped with the s-box entry indexed by the second|
-number of the pair. This process continues until all pairs have been|
-processed, which stops at the end of the input data stream.|
-|
-"E" ... <pairs>: Exactly like "D", only that the reverse transformation is|
-done, emitting the encrypted values of the decrypted first numbers in all the|
-pairs. The second number must be the same as was used for decryption.|
-Encryption requires more work than decryption and is therefore slower. This|
-is a deliberate design decision, because data usually gets at least as often|
-decrypted as it has been encrypted, and potentially more often. If this is|
-not true for your application (i. e. encrypting backups), the "D" and "E"|
-operations can be exchanged without security disadvantages: They are just the|
-inverses of one another. It is not really important which of both|
-transformation is used for encryption and which one for decryption.|
+<pairs>: Transform (or inversely transform, selected by command line option) |
+all following input data, interpreting it as an arbitrary number of pairs of |
+decimal values. The first value in every pair is a value to be transformed |
+(back), and the second value must have been created by a cryptographic |
+pseudo-random generator. The tranformation consists of emitting the current |
+s-box value indexed by the first value. After this, the s-box entry just |
+output is swapped with the s-box entry indexed by the second value of the |
+pair. The inverse transformation does the opposite of these steps. This |
+process continues until all pairs have been transformed or been transformed |
+back, which stops at the end of the input data stream.|
 |
 |
 All "<...>" items explained above must be unsigned decimal integer numbers in |
 ASCII encoding.|
 |
-The output of $APP will also be ASCII decimal number with 20 numbers per line |
+The output of $APP will also be ASCII decimal number with 20 values per line |
 (except for the last line which might be shorter).|
 |
 |
 Options supported:|
 |
+-e: Apply the inverse transformation. This is slower. Normally used for |
+encryption.|
+-d: Apply the transformation. This is faster. Normally used for decryption.|
 -V: Show version information and exit.|
 -h: Display this help and exit.|
 |
 |
-This utility is intended to be used together with a companion utility which|
-can interleave the data values to be encrypted with pseudorandom values|
-generated by a cryptographically secure pseudo random generator. That utility|
-can also prefix the interleaved data stream with 256 pseudorandom numbers to|
-be used as <key256>.|
+There is no real reason why -d applies the transformation and -e applies the |
+inverse transformation. It could be the other way around as well. Both |
+transformations just undo the effects of the other one. The decision to use |
+the slower transformation for encryption has been made due to the observation |
+that most data will be decrypted at least as often as it has been encrypted, |
+and sometimes more often than that.|
 |
-The output of this utility is intended to be used together with another|
-companion utility which can convert the encrypted or decrypted decimal|
-numbers into binary output data.|
+However, there are scenarios where this does not necessarily apply, such as |
+encrypting backups. Feel free to reverse the options -e and -d for such |
+applications; this will have no adverse effect on the encryption security.|
+|
+This utility is intended to be used together with a companion utility |
+"rc4csprng10" which can interleave the data values to be encrypted with |
+pseudorandom values generated by a cryptographically secure pseudo random |
+generator. That utility can also prefix the interleaved data stream with 256 |
+pseudorandom values to be used as <key256>.|
+|
+The output of this utility is intended to be used together with another |
+companion utility "dec2raw" which can convert the encrypted or decrypted |
+decimal values into binary output data.|
 ===
 }
 APP=${0##*/}
@@ -100,9 +101,12 @@ exit_help() {
 	echo; exit_version "$@"
 }
 
-while getopts d:g:hV opt
+mode=
+while getopts dehV opt
 do
 	case $opt in
+		e) mode=E;;
+		d) mode=D;;
 		h) exit_help;;
 		V) exit_version;;
 		*) false || exit
@@ -110,35 +114,32 @@ do
 done
 shift `expr $OPTIND - 1 || :`
 
-case $# in
-	0) ;;
+case $mode:$# in
+	?:0) ;;
 	*) exit_help `false || echo $?` >& 2
 esac
 
-awk -v failure=`false || echo $?` -f /dev/fd/5 5<< 'EOF'
+awk -v mode=$mode -v failure=`false || echo $?` -f /dev/fd/5 5<< 'EOF'
 
-# Globals: si, mode, oitems, oline, s[256], rs[256].
+# Globals: failure, phase, si, mode, oitems, oline, s[256], rs[256].
 
 BEGIN {
-	init_sbox(); si= 0
+	init_sbox(); si= 0; phase= "K"
 }
 
 {
 	for (i= 1; i <= NF; ++i) {
-		if (mode == "D") {
-			if (si < 0) si= $i; else emit(decrypt($i))
-		} else if (mode == "E") {
-			if (si < 0) si= $i; else emit(encrypt($i))
-		} else if ($i ~ /^[DE]$/) {
-			if (si) die("'D' or 'E' token must come first!")
-			mode= "K" $i
-		} else {
+		if (phase == "K") {
 			append_key_octet($i)
 			if (si == 256) {
-				mode= substr(mode, 2)
+				phase= "T"
 				if (mode == "E") calc_rev_sbox()
 				si= -1
 			}
+		} else if(mode == "D") {
+			if (si < 0) si= $i; else emit(decrypt($i))
+		} else {
+			if (si < 0) si= $i; else emit(encrypt($i))
 		}
 	}
 }
